export const testIds = {
  appConfig: {
    a2aBaseUrl: 'data-testid ac-a2a-base-url',
    apiKey: 'data-testid ac-api-key',
    streamingEnabled: 'data-testid ac-streaming-enabled',
    submit: 'data-testid ac-submit-form',
    testConnection: 'data-testid ac-test-connection',
    testConnectionSuccess: 'data-testid ac-test-connection-success',
    testConnectionError: 'data-testid ac-test-connection-error',
  },
  chat: {
    page: 'data-testid chat-page',
    sidebar: 'data-testid chat-sidebar',
    sidebarToggle: 'data-testid chat-sidebar-toggle',
    sidebarBackdrop: 'data-testid chat-sidebar-backdrop',
    conversationItem: 'data-testid chat-conversation-item',
    newChatButton: 'data-testid chat-new-chat',
    deleteConversationButton: 'data-testid chat-delete-conversation',
    messageList: 'data-testid chat-message-list',
    userMessage: 'data-testid chat-user-message',
    assistantMessage: 'data-testid chat-assistant-message',
    typingIndicator: 'data-testid chat-typing-indicator',
    composer: 'data-testid chat-composer',
    composerInput: 'data-testid chat-composer-input',
    sendButton: 'data-testid chat-send-button',
    stopButton: 'data-testid chat-stop-button',
    emptyState: 'data-testid chat-empty-state',
    errorBanner: 'data-testid chat-error-banner',
  },
};
